[package]
name = "serbian-transliterator-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

# === OPTIMIZACIJA ZA VELIČINU (RELEASE) ===
[profile.release]
opt-level = "z"   # Optimizuj za veličinu
lto = true        # Link Time Optimization
codegen-units = 1 # Manje paralelizma = bolja optimizacija
strip = true      # Ukloni simbole
panic = "abort"   # Ukloni panic unwinding kod
