// src/shared/ooxml/roman.ts
export const ROMAN_REGEX_STRICT =
    /\b(?!I\b)(?=[MDCLXVI]+\b)M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})\b/g;

const ROMAN_I_PREFIXES = [
    "Petar",
    "Aleksandar",
    "Pavle",
    "Đorđe",
    "Djordje",
    "Milan",
    "Miloš",
    "Milos",
    "Katarina",
    "Elizabeta",
    "Viktorija",
    "Marija",
    "Ana",
    "Luj",
    "Šarl",
    "Sarl",
    "Anri",
    "Filip",
    "Felipe",
    "Huan",
    "Karlos",
    "Viljem",
    "Fridrih",
    "Oskar",
    "Gustav",
    "Erik",
    "Jovan",
    "Jozef",
    "Benedikt",
    "Pije",
    "Lav",
    "Grgur",
    "Klement",
    "Inoćentije",
    "Nikola",
    "Napoleon",
    "Konstantin",
    "Stefan",
    "Uroš",
    "Uros",
    "Dušan",
    "Dusan",
    "Član",
    "Clan",
    "Glava",
    "Deo",
    "Stav",
    "Tačka",
    "Tacka",
    "Odeljak",
    "Aneks",
    "Klasa",
    "Grupa",
    "Tom",
    "Knjiga",
    "Sveska",
    "Partija",
    "Zona",
    "Sektor",
    "Svetski rat",
    "Boj",
    "Put",
];

export const ROMAN_I_REGEX = new RegExp(`\\b(${ROMAN_I_PREFIXES.join("|")})\\s+I\\b`, "g");
